import assert from "node:assert/strict";
import test from "node:test";
import { aggregateDaily, aggregateWeekly, buildBaseline, calculateVli, evaluateNearWorkPattern, localDateFor, validateAnalyticsInput } from "../../personal-intelligence/analytics.js";

const valid = { sourceId: "work-0001", sourceType: "WORK_SESSION" as const, occurredAtUtc: "2026-07-14T10:00:00.000Z", timezone: "Asia/Bangkok", schemaVersion: "m2-session-summary/0.1.0", algorithmVersion: "m2-companion-policy/0.1.0", quality: "VALID" as const, contextKey: "timer-only", sessionDurationMinutes: 30, breakCompliance: 40, symptomBurden: null, nearLoad: 80, distanceDeviation: null, blinkDeviation: null };
test("canonical input rejects invalid numeric and preserves unknown", () => { assert.equal(validateAnalyticsInput(valid).symptomBurden, null); assert.throws(() => validateAnalyticsInput({ ...valid, nearLoad: Number.NaN }), /INVALID_ANALYTICS_INPUT/); });
test("baseline uses sample coverage and supports reset/stale", () => { const inputs = [valid, { ...valid, sourceId: "work-0002" }, { ...valid, sourceId: "work-0003" }]; assert.equal(buildBaseline(inputs, "timer-only", { version: "base/1", minimumSamples: 3, staleAfterDays: 7 }, "2026-07-15T00:00:00.000Z").state, "READY"); assert.equal(buildBaseline(inputs, "timer-only", { version: "base/1", minimumSamples: 3, staleAfterDays: 1 }, "2026-07-20T00:00:00.000Z").state, "STALE"); assert.equal(buildBaseline(inputs, "timer-only", { version: "base/1", minimumSamples: 3, staleAfterDays: 1 }, "2026-07-20T00:00:00.000Z", true).state, "RESET"); });
test("VLI excludes missing values rather than treating them as zero", () => { const partial = calculateVli(valid); assert.equal(partial.status, "AVAILABLE"); assert.deepEqual([...partial.missingComponents].sort(), ["blinkDeviation", "distanceDeviation", "symptomBurden"].sort()); assert.equal(calculateVli({ ...valid, nearLoad: null, breakCompliance: null }).status, "INSUFFICIENT_DATA"); });
test("pattern abstains when required evidence is missing", () => { assert.equal(evaluateNearWorkPattern(valid, "2026-07-14T12:00:00.000Z").status, "PRESENT"); assert.equal(evaluateNearWorkPattern({ ...valid, nearLoad: null }, "2026-07-14T12:00:00.000Z").status, "INSUFFICIENT_DATA"); });
test("daily and weekly keep missing coverage explicit", () => { const daily = aggregateDaily([valid], "2026-07-14", "Asia/Bangkok"); assert.equal(daily.status, "AVAILABLE"); assert.equal(aggregateWeekly([daily], "2026-07-14", "Asia/Bangkok").status, "INSUFFICIENT_DATA"); });
test("daily grouping uses recorded IANA timezone rather than UTC date", () => assert.equal(localDateFor("2026-07-13T18:00:00.000Z", "Asia/Bangkok"), "2026-07-14"));
